/* ============================================================
   PRODUCT CATALOG — Category-wise product data
   ============================================================ */
export const CATALOG_CATEGORIES = [
  {
    id: "all",
    name: "All Products",
   
    description: "Browse our complete product portfolio",
  },
  {
    id: "rice",
    name: "Rice",
   
    description:
      "Long-grain 1121 Basmati and Biryani rice, export-packed for Gulf and domestic trade.",
  },
  {
    id: "mustard-oil",
    name: "Mustard Oil",
  
    description: "Pure and authentic Kachi Ghani Mustard Oil for domestic retail.",
  },
  {
    id: "spices",
    name: "Spices",

    description:
      "Taste With Purity – finely ground, 100% natural spice powders.",
  },
  {
    id: "pulses",
    name: "Pulses",

    description:
      "Premium-quality pulses, naturally sourced and carefully cleaned to preserve authentic taste and nutrition.",
  },
  {
    id: "makhana",
    name: "Makhana",
  
    description:
      "Premium, naturally wholesome makhana, carefully selected for light, crispy texture and authentic taste.",
  },
];

export const CATALOG_PRODUCTS = [
  {
    id: "p001",
    name: " Sella Basmati Rice",
    category: "rice",
    categoryLabel: "Rice",
    description: "Extra-long grain 1121 Sella Basmati, aged for perfect aroma.",
    badge: "Export Quality",
    badgeColor: "gold",
    image: "https://ik.imagekit.io/deep1125/bito/Rice%207.png?updatedAt=1788767650623",
  },
  {
    id: "p002",
    name: "Long Grain Biryani Rice",
    category: "rice",
    categoryLabel: "Rice",
    description: "Premium long-grain rice ideal for biryani and pulao.",
    badge: "Premium",
    badgeColor: "premium",
    image: "https://ik.imagekit.io/deep1125/bito/Rice%208.png?updatedAt=1788767650469",
  },
  {
    id: "p003",
    name: "Indian Long Grain Basmati Rice",
    category: "rice",
    categoryLabel: "Rice",
    description: "Authentic Indian Basmati with signature elongation.",
    badge: "Export Quality",
    badgeColor: "gold",
    image: "https://ik.imagekit.io/deep1125/bito/Rice%206.png?updatedAt=1788767650656",
  },
  {
    id: "p004",
    name: "Premium  Basmati Rice",
    category: "rice",
    categoryLabel: "Rice",
    description: "Steam-processed 1121 Basmati retaining nutrition.",
    badge: "Premium",
    badgeColor: "premium",
    image: "https://ik.imagekit.io/deep1125/bito/Rice%201.png?updatedAt=1788767650366",
  },
 
  {
    id: "p007",
    name: "Kachi Ghani Mustard Oil – 1L",
    category: "mustard-oil",
    categoryLabel: "Mustard Oil",
    description: "Cold-pressed pure Kachi Ghani Mustard Oil, FSSAI certified.",
    badge: "Domestic",
    badgeColor: "green",
    image: "https://ik.imagekit.io/deep1125/bito/Sarso%20oil%202.png?updatedAt=1788767650046",
  },
  {
    id: "p008",
    name: "Black Pepper Powder – 100g",
    category: "spices",
    categoryLabel: "Spices",
    description: "Finely ground 100% natural black pepper powder.",
    badge: "Domestic",
    badgeColor: "green",
    image: "https://ik.imagekit.io/deep1125/bito/Black%20pepper.png?updatedAt=1788767650610",
  },
  {
    id: "p009",
    name: "Turmeric Powder – 100g",
    category: "spices",
    categoryLabel: "Spices",
    description: "Pure turmeric powder with high curcumin content.",
    badge: "Premium",
    badgeColor: "premium",
    image: "https://ik.imagekit.io/deep1125/bito/Haldi.png?updatedAt=1788767650319",
  },
  {
    id: "p010",
    name: "Red Chilli Powder – 100g",
    category: "spices",
    categoryLabel: "Spices",
    description: "Bright red chilli powder with balanced heat.",
    badge: "Export Quality",
    badgeColor: "gold",
    image: "https://ik.imagekit.io/deep1125/bito/Red%20Chilli.png?updatedAt=1788767650589",
  },
  {
    id: "p011",
    name: "Sabzi Masala Powder – 100g",
    category: "spices",
    categoryLabel: "Spices",
    description: "All-in-one blended masala for vegetables & curries.",
    badge: "Domestic",
    badgeColor: "green",
    image: "https://ik.imagekit.io/deep1125/bito/Sabzi%20mashala.png?updatedAt=1788767650600",
  },
  {
    id: "p012",
    name: "Coriander Powder – 100g",
    category: "spices",
    categoryLabel: "Spices",
    description: "Freshly ground coriander seed powder.",
    badge: "Premium",
    badgeColor: "premium",
    image: "https://ik.imagekit.io/deep1125/bito/Dhaniya.png?updatedAt=1788767650604",
  },
  {
    id: "p013",
    name: "Toor Dal",
    category: "pulses",
    categoryLabel: "Pulses",
    description: "Premium Toor Dal, machine-cleaned and sortex-graded.",
    badge: "Domestic",
    badgeColor: "green",
    image: "https://ik.imagekit.io/deep1125/bito/Toor%20Dal.png?updatedAt=1788767650076",
  },
  {
    id: "p014",
    name: "Moong Dal",
    category: "pulses",
    categoryLabel: "Pulses",
    description: "Split and polished Moong Dal with vibrant yellow color.",
    badge: "Premium",
    badgeColor: "premium",
    image: "https://ik.imagekit.io/deep1125/bito/Moong%20dal.png?updatedAt=1788767650357",
  },
  {
    id: "p015",
    name: "Matar Dal",
    category: "pulses",
    categoryLabel: "Pulses",
    description: "Green split peas with sweet, earthy flavor.",
    badge: "Domestic",
    badgeColor: "green",
    image: "https://ik.imagekit.io/deep1125/bito/Matar%20dal.png?updatedAt=1788767649854",
  },
  {
    id: "p016",
    name: "Chana Dal",
    category: "pulses",
    categoryLabel: "Pulses",
    description: "Split Bengal gram with nutty taste and firm texture.",
    badge: "Export Quality",
    badgeColor: "gold",
    image: "https://ik.imagekit.io/deep1125/bito/chana%20dal.png?updatedAt=1788767649992",
  },
  {
    id: "p017",
    name: "Urad Dal",
    category: "pulses",
    categoryLabel: "Pulses",
    description: "Whole and split Urad Dal for South Indian cuisine.",
    badge: "Premium",
    badgeColor: "premium",
    image: "https://ik.imagekit.io/deep1125/bito/Urad%20dal.png?updatedAt=1788767650536",
  },
  {
    id: "p018",
    name: "Masoor Dal",
    category: "pulses",
    categoryLabel: "Pulses",
    description: "Red lentils — fast-cooking, high-protein staple.",
    badge: "Domestic",
    badgeColor: "green",
    image: "https://ik.imagekit.io/deep1125/bito/Masoor%20Dal.png?updatedAt=1788767650003",
  },
  {
    id: "p019",
    name: "Classic 6 Suta Makhana",
    category: "makhana",
    categoryLabel: "Makhana",
    description: "Grade-A 6 Suta Makhana — light, crispy fox nuts.",
    badge: "Domestic",
    badgeColor: "green",
    image: "https://ik.imagekit.io/deep1125/bito/6%20Suta%20makhana.png?updatedAt=1788767649363",
  },
  {
    id: "p020",
    name: "Premium 7 Suta Makhana",
    category: "makhana",
    categoryLabel: "Makhana",
    description: "Larger 7 Suta grade with superior expansion.",
    badge: "Premium",
    badgeColor: "premium",
    image: "https://ik.imagekit.io/deep1125/bito/7%20Suta%20makhana.png?updatedAt=1788767649628",
  },
  {
    id: "p021",
    name: "Royal 8 Suta Makhana",
    category: "makhana",
    categoryLabel: "Makhana",
    description: "Top-tier 8 Suta Makhana — extra-large, perfectly popped.",
    badge: "Export Quality",
    badgeColor: "gold",
    image: "https://ik.imagekit.io/deep1125/bito/8%20Suta%20makhana.png?updatedAt=1788767650032",
  },
  {
    id: "p022",
    name: "Grand 9 Suta Makhana",
    category: "makhana",
    categoryLabel: "Makhana",
    description: "Ultra-premium 9 Suta — the largest grade available.",
    badge: "Export Quality",
    badgeColor: "gold",
    image: "https://ik.imagekit.io/deep1125/bito/9%20suta%20makhana.png?updatedAt=1788767649834",
  },
  {
    id: "p023",
    name: "Crispy Roasted Makhana",
    category: "makhana",
    categoryLabel: "Makhana",
    description: "Ready-to-eat roasted makhana — guilt-free snacking.",
    badge: "Premium",
    badgeColor: "premium",
    image: "https://ik.imagekit.io/deep1125/bito/BW%20Crispy%20Makhana.png?updatedAt=1788767649961",
  },
  {
    id: "p024",
    name: "Desi Masala Makhana",
    category: "makhana",
    categoryLabel: "Makhana",
    description: "Indian masala-flavored roasted makhana.",
    badge: "Domestic",
    badgeColor: "green",
    image: "https://ik.imagekit.io/deep1125/bito/BW%20Desi%20Makhana.png?updatedAt=1788767650344",
  },
];
